# Generated by Django 3.2.8 on 2024-08-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('custom_fields', models.TextField(blank=True, default='{}')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
