# Generated by Django 3.2.8 on 2024-08-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
